export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id:string; display_name:string|null; avatar_url:string|null; role:'user'|'admin'; created_at:string; updated_at:string }; Insert: { id:string; display_name?:string|null; avatar_url?:string|null; role?:'user'|'admin' }; Update: { display_name?:string|null; avatar_url?:string|null } };
      categories: { Row: { id:string; name:string; slug:string; description:string|null; icon:string|null; sort_order:number; is_active:boolean; created_at:string; updated_at:string }; Insert: never; Update: never };
      topics: { Row: { id:string; category_id:string; name:string; slug:string; description:string|null; cover_image_path:string|null; summary_card_image_path:string|null; sort_order:number; is_free:boolean; is_active:boolean; created_at:string; updated_at:string }; Insert: never; Update: never };
      knowledge_cards: { Row: { id:string; topic_id:string; slug:string; status:'draft'|'published'|'archived'; question_type:'choice'|'recall'; question:string; answer:string; explanation:string; mnemonic:string|null; mistake_tip:string|null; related_knowledge:Json; option_a:string|null; option_b:string|null; option_c:string|null; option_d:string|null; correct_option:'A'|'B'|'C'|'D'|null; question_image_path:string|null; answer_image_path:string|null; question_thumbnail_path:string|null; answer_thumbnail_path:string|null; image_alt:string|null; difficulty:1|2|3; is_free:boolean; sort_order:number; published_at:string|null; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['knowledge_cards']['Row']> & Pick<Database['public']['Tables']['knowledge_cards']['Row'],'topic_id'|'slug'|'question'|'answer'|'explanation'>; Update: Partial<Database['public']['Tables']['knowledge_cards']['Row']> };
      user_card_progress: { Row: { id:string; user_id:string; card_id:string; status:'new'|'learning'|'reviewing'|'mastered'; last_rating:'forgot'|'fuzzy'|'remembered'|null; review_count:number; correct_count:number; wrong_count:number; correct_streak:number; last_reviewed_at:string|null; next_review_at:string|null; is_mastered:boolean; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['user_card_progress']['Row']> & Pick<Database['public']['Tables']['user_card_progress']['Row'],'user_id'|'card_id'>; Update: Partial<Database['public']['Tables']['user_card_progress']['Row']> };
      favorites: { Row: { id:string; user_id:string; card_id:string; created_at:string }; Insert: { user_id:string; card_id:string }; Update: never };
      wrong_answers: { Row: { id:string; user_id:string; card_id:string; last_selected_option:string|null; wrong_count:number; last_wrong_at:string; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['wrong_answers']['Row']> & Pick<Database['public']['Tables']['wrong_answers']['Row'],'user_id'|'card_id'>; Update: Partial<Database['public']['Tables']['wrong_answers']['Row']> };
      study_sessions: { Row: { id:string; user_id:string; started_at:string; ended_at:string|null; new_count:number; review_count:number; remembered_count:number; fuzzy_count:number; forgot_count:number; duration_seconds:number; created_at:string }; Insert: Omit<Database['public']['Tables']['study_sessions']['Row'],'id'|'created_at'>; Update: never };
      user_settings: { Row: { user_id:string; daily_new_count:number; daily_review_limit:number; study_mode:'smart'|'choice'|'recall'; auto_next:boolean; show_shortcut_hint:boolean; updated_at:string }; Insert: Partial<Database['public']['Tables']['user_settings']['Row']> & Pick<Database['public']['Tables']['user_settings']['Row'],'user_id'>; Update: Partial<Database['public']['Tables']['user_settings']['Row']> };
    };
    Views: Record<string, never>; Functions: Record<string, never>; Enums: Record<string, never>; CompositeTypes: Record<string, never>;
  };
};
