import { supabase } from '../../lib/supabase/client';
import { supabaseErrorMessage } from '../../lib/supabase/errors';
import type { Rating, ReviewRecord, StudySession, UserSettings } from '../../types/review';
import { applyRating } from '../../lib/scheduler';
import { loadRecords, loadSessions, loadSettings } from '../../lib/storage';

export async function saveCloudRating(userId:string, cardId:string, previous:ReviewRecord|undefined, rating:Rating) { if(!supabase) return; const db:any=supabase; const local=applyRating(previous,cardId,rating); const payload={user_id:userId,card_id:cardId,status:local.status,last_rating:rating,review_count:local.reviewCount,correct_count:rating==='remembered'?(previous?.reviewCount ?? 0)+1:0,wrong_count:local.mistakeCount,correct_streak:local.correctStreak,last_reviewed_at:local.lastReviewedAt,next_review_at:local.nextReviewAt,is_mastered:local.status==='mastered'}; const {error}=await db.from('user_card_progress').upsert(payload,{onConflict:'user_id,card_id'}); if(error) throw new Error(supabaseErrorMessage(error)); if(rating==='forgot'){const {data}=await db.from('wrong_answers').select('wrong_count').eq('user_id',userId).eq('card_id',cardId).maybeSingle(); const {error:wrongError}=await db.from('wrong_answers').upsert({user_id:userId,card_id:cardId,wrong_count:(data?.wrong_count ?? 0)+1,last_wrong_at:new Date().toISOString()},{onConflict:'user_id,card_id'}); if(wrongError) throw new Error(supabaseErrorMessage(wrongError));} }
export async function syncFavorite(userId:string, cardId:string, favorite:boolean) { if(!supabase) return; const db:any=supabase; const result=favorite ? await db.from('favorites').upsert({user_id:userId,card_id:cardId},{onConflict:'user_id,card_id'}) : await db.from('favorites').delete().eq('user_id',userId).eq('card_id',cardId); if(result.error) throw new Error(supabaseErrorMessage(result.error)); }
export async function saveCloudSession(userId:string, session:StudySession) { if(!supabase) return; const db:any=supabase; const ratings=session.ratings; const {error}=await db.from('study_sessions').insert({user_id:userId,started_at:session.startedAt,ended_at:session.completedAt,new_count:session.cardIds.length,review_count:0,remembered_count:ratings.filter(x=>x==='remembered').length,fuzzy_count:ratings.filter(x=>x==='fuzzy').length,forgot_count:ratings.filter(x=>x==='forgot').length,duration_seconds:Math.max(0,Math.round((new Date(session.completedAt).getTime()-new Date(session.startedAt).getTime())/1000))}); if(error) throw new Error(supabaseErrorMessage(error)); }
export async function mergeLocalData(userId:string, cloudCards:Array<{id:string;question:string}>) { if(!supabase) return; const db:any=supabase; const localRecords=loadRecords(); const localCards=(await import('../../data/cards')).cards; const questionById=new Map(localCards.map(card=>[card.id,card.question])); const index=new Map(cloudCards.map(card=>[card.question,card.id])); const progress=Object.entries(localRecords).flatMap(([localId,record])=>{const cardId=cloudCards.some(item=>item.id===localId)?localId:index.get(questionById.get(localId)??''); return cardId?[{user_id:userId,card_id:cardId,status:record.status,last_rating:record.lastRating ?? null,review_count:record.reviewCount,correct_count:record.correctStreak,wrong_count:record.mistakeCount,correct_streak:record.correctStreak,last_reviewed_at:record.lastReviewedAt ?? null,next_review_at:record.nextReviewAt ?? null,is_mastered:record.status==='mastered'}]:[];}); if(progress.length){const {error}=await db.from('user_card_progress').upsert(progress,{onConflict:'user_id,card_id'});if(error)throw new Error(supabaseErrorMessage(error));} const localSettings=loadSettings(); const {error:settingsError}=await db.from('user_settings').upsert({user_id:userId,daily_new_count:localSettings.dailyNewCount,daily_review_limit:localSettings.dailyReviewLimit,auto_next:localSettings.autoNext,show_shortcut_hint:localSettings.showShortcutHint},{onConflict:'user_id'});if(settingsError)throw new Error(supabaseErrorMessage(settingsError)); const sessions=loadSessions(); if(sessions.length){await Promise.all(sessions.slice(0,50).map(session=>saveCloudSession(userId,session)));} }
