import { supabase } from '../../lib/supabase/client';
import { supabaseErrorMessage } from '../../lib/supabase/errors';
import type { ImportRow } from './csv';

export type AdminCategory = { id: string; name: string; slug: string; sort_order: number; is_active: boolean };
export type AdminTopic = { id: string; name: string; slug: string; category_id: string; category_name: string; sort_order: number; is_free: boolean; is_active: boolean; description: string | null };
export type OptionKey = 'A' | 'B' | 'C' | 'D' | 'E';
export type AdminCard = { id: string; topic_id: string; topic_name: string; category_name: string; slug: string; status: 'draft' | 'published' | 'archived'; question_type: 'choice' | 'multiple' | 'recall'; question: string; answer: string; explanation: string; mnemonic: string | null; mistake_tip: string | null; option_a: string | null; option_b: string | null; option_c: string | null; option_d: string | null; option_e: string | null; correct_option: OptionKey | null; correct_options: OptionKey[]; difficulty: 1 | 2 | 3; is_free: boolean; sort_order: number; question_image_path: string | null; answer_image_path: string | null; question_thumbnail_path: string | null; answer_thumbnail_path: string | null; image_alt: string | null };
export type CardInput = Omit<AdminCard, 'id' | 'topic_name' | 'category_name' | 'question_image_path' | 'answer_image_path' | 'question_thumbnail_path' | 'answer_thumbnail_path'> & { question_image_path?: string | null; answer_image_path?: string | null; question_thumbnail_path?: string | null; answer_thumbnail_path?: string | null };
export type TopicInput = Pick<AdminTopic, 'category_id' | 'name' | 'slug' | 'sort_order' | 'is_free' | 'is_active' | 'description'>;

function client() { if (!supabase) throw new Error('Supabase 尚未配置。'); return supabase as any; }
function mapTopic(row: any): AdminTopic { return { ...row, category_name: row.categories?.name ?? '未分类' }; }
function mapCard(row: any): AdminCard { return { ...row, topic_name: row.topics?.name ?? '未分类', category_name: row.topics?.categories?.name ?? '未分类' }; }

export async function getAdminCategories() { const { data, error } = await client().from('categories').select('id,name,slug,sort_order,is_active').order('sort_order'); if (error) throw new Error(supabaseErrorMessage(error)); return (data ?? []) as AdminCategory[]; }
export async function getAdminTopics() { const { data, error } = await client().from('topics').select('id,name,slug,category_id,sort_order,is_free,is_active,description,categories(name)').order('sort_order'); if (error) throw new Error(supabaseErrorMessage(error)); return (data ?? []).map(mapTopic); }
export async function getAdminCards() { const { data, error } = await client().from('knowledge_cards').select('id,topic_id,slug,status,question_type,question,answer,explanation,mnemonic,mistake_tip,option_a,option_b,option_c,option_d,option_e,correct_option,correct_options,difficulty,is_free,sort_order,question_image_path,answer_image_path,question_thumbnail_path,answer_thumbnail_path,image_alt,topics(name,categories(name))').order('updated_at', { ascending: false }); if (error) throw new Error(supabaseErrorMessage(error)); return (data ?? []).map(mapCard); }
export async function getAdminCard(id: string) { const { data, error } = await client().from('knowledge_cards').select('id,topic_id,slug,status,question_type,question,answer,explanation,mnemonic,mistake_tip,option_a,option_b,option_c,option_d,option_e,correct_option,correct_options,difficulty,is_free,sort_order,question_image_path,answer_image_path,question_thumbnail_path,answer_thumbnail_path,image_alt,topics(name,categories(name))').eq('id', id).maybeSingle(); if (error) throw new Error(supabaseErrorMessage(error)); return data ? mapCard(data) : null; }
export async function saveCard(input: CardInput, id?: string) { const db = client(); const correct_options = input.question_type === 'multiple' ? input.correct_options : input.question_type === 'choice' && input.correct_option ? [input.correct_option] : []; const payload = { ...input, correct_option: input.question_type === 'choice' ? input.correct_option : null, correct_options, published_at: input.status === 'published' ? new Date().toISOString() : null }; const result = id ? await db.from('knowledge_cards').update(payload).eq('id', id).select('id').single() : await db.from('knowledge_cards').insert(payload).select('id').single(); if (result.error) throw new Error(supabaseErrorMessage(result.error)); return result.data.id as string; }
export async function updateCardStatus(id: string, status: AdminCard['status']) { const { error } = await client().from('knowledge_cards').update({ status, published_at: status === 'published' ? new Date().toISOString() : null }).eq('id', id); if (error) throw new Error(supabaseErrorMessage(error)); }
export async function saveTopic(input: TopicInput, id?: string) { const db = client(); const result = id ? await db.from('topics').update(input).eq('id', id) : await db.from('topics').insert(input); if (result.error) throw new Error(supabaseErrorMessage(result.error)); }
export async function swapTopicOrder(first: AdminTopic, second: AdminTopic) { const db = client(); const [a, b] = await Promise.all([db.from('topics').update({ sort_order: second.sort_order }).eq('id', first.id), db.from('topics').update({ sort_order: first.sort_order }).eq('id', second.id)]); if (a.error) throw new Error(supabaseErrorMessage(a.error)); if (b.error) throw new Error(supabaseErrorMessage(b.error)); }
export async function uploadCardImage(path: string, file: File) { const { error } = await client().storage.from('card-images').upload(path, file, { upsert: false, cacheControl: '31536000', contentType: 'image/webp' }); if (error) throw new Error(supabaseErrorMessage(error)); return path; }
export async function bindCardImages(slug: string, kind: 'question' | 'answer', fullPath: string, thumbnailPath: string) { const payload = kind === 'question' ? { question_image_path: fullPath, question_thumbnail_path: thumbnailPath } : { answer_image_path: fullPath, answer_thumbnail_path: thumbnailPath }; const { data, error } = await client().from('knowledge_cards').update(payload).eq('slug', slug).select('id').maybeSingle(); if (error) throw new Error(supabaseErrorMessage(error)); if (!data) throw new Error(`未找到 slug 为「${slug}」的知识点，图片未绑定。`); }
export async function importCards(rows: ImportRow[], topics: AdminTopic[]) { const db = client(); const topicIndex = new Map(topics.map(topic => [topic.slug, topic.id])); for (let index = 0; index < rows.length; index += 50) { const batch = rows.slice(index, index + 50).filter(row => !row.error).map(row => { const topicId = topicIndex.get(row.topic_slug); if (!topicId) throw new Error(`专题 slug「${row.topic_slug}」不存在，请先在专题管理中创建。`); const correct_options = row.question_type === 'multiple' ? row.correct_options.split('|').filter(Boolean) : row.question_type === 'choice' && row.correct_option ? [row.correct_option] : []; return { topic_id: topicId, slug: row.slug, status: row.status, question_type: row.question_type, question: row.question, option_a: row.option_a || null, option_b: row.option_b || null, option_c: row.option_c || null, option_d: row.option_d || null, option_e: row.option_e || null, correct_option: row.question_type === 'choice' ? row.correct_option || null : null, correct_options, answer: row.answer, explanation: row.explanation, mnemonic: row.mnemonic || null, mistake_tip: row.mistake_tip || null, difficulty: Number(row.difficulty), is_free: row.is_free !== 'false', sort_order: Number(row.sort_order || 0), published_at: row.status === 'published' ? new Date().toISOString() : null }; }); const { error } = await db.from('knowledge_cards').upsert(batch, { onConflict: 'slug' }); if (error) throw new Error(supabaseErrorMessage(error)); } }
export async function estimateUsage() { const db = client(); const [{ count: cardCount }, { count: topicCount }, { data: files }] = await Promise.all([db.from('knowledge_cards').select('*', { count: 'exact', head: true }), db.from('topics').select('*', { count: 'exact', head: true }), supabase!.storage.from('card-images').list('', { limit: 1000 })]); const bytes = (files ?? []).reduce((sum: number, file: any) => sum + (file.metadata?.size ?? 0), 0); return { cardCount: cardCount ?? 0, topicCount: topicCount ?? 0, imageCount: files?.length ?? 0, bytes, average: (files?.length ?? 0) ? bytes / (files?.length ?? 1) : 0 }; }
