import { useEffect,useRef,useState } from 'react';
import { Link } from 'react-router-dom';
import { EmptyState } from '../../components/EmptyState';
import { getAdminTopics, estimateUsage, importCards, uploadCardImage } from './adminRepository';
import { matchImageFilename, parseCsv, type ImportRow } from './csv';
import { prepareCardImages } from '../../lib/images/compressImage';

export function AdminGuard({isAdmin,children}:{isAdmin:boolean;children:React.ReactNode}){return isAdmin?<>{children}</>:<EmptyState title="没有管理权限" description="此区域仅对 Supabase 管理员开放。" to="/account" action="返回账户"/>;}
export function AdminHome(){return <section className="admin-page"><p className="eyebrow">管理员后台</p><h1>题库与漫画内容管理</h1><div className="admin-grid"><Link to="/admin/cards/new">新建知识点</Link><Link to="/admin/import">CSV 批量导入</Link><Link to="/admin/storage">批量漫画匹配</Link><Link to="/admin/usage-guide">免费额度估算</Link><Link to="/admin/topics">专题管理</Link></div></section>}
export function ImportPage(){const [rows,setRows]=useState<ImportRow[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const upload=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setRows(parseCsv(String(reader.result)));reader.readAsText(file,'utf-8')};const save=async()=>{setBusy(true);try{const topics=await getAdminTopics();await importCards(rows.filter(r=>!r.error),topics);setMessage(`已提交 ${rows.filter(r=>!r.error).length} 条知识点。`)}catch(error){setMessage(error instanceof Error?error.message:'导入失败。')}finally{setBusy(false)}};return <section className="admin-page"><Link to="/admin">← 返回后台</Link><h1>CSV 批量导入</h1><p>每批最多 50 条；有错误的行不会提交。</p><input type="file" accept=".csv,text/csv" onChange={e=>upload(e.target.files?.[0])}/>{rows.length>0&&<><div className="import-summary">共 {rows.length} 行，可导入 {rows.filter(r=>!r.error).length} 行，错误 {rows.filter(r=>r.error).length} 行。</div><div className="table-wrap"><table><thead><tr><th>行</th><th>slug</th><th>问题</th><th>检查</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr><td>{r.line}</td><td>{r.slug}</td><td>{r.question}</td><td>{r.error??'可导入'}</td></tr>)}</tbody></table></div><button className="btn primary" disabled={busy||!rows.some(r=>!r.error)} onClick={save}>{busy?'正在导入…':'确认导入'}</button></>}{message&&<p className="form-message">{message}</p>}</section>}
export function StoragePage(){const [files,setFiles]=useState<File[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const pick=(list:FileList|null)=>setFiles(list?Array.from(list):[]);const upload=async()=>{setBusy(true);try{for(let i=0;i<files.length;i+=5){for(const file of files.slice(i,i+5)){const parsed=matchImageFilename(file.name);if(!parsed)continue;const images=await prepareCardImages(file);const base=`cards/import/${parsed.slug}-${parsed.kind}-${Date.now()}`;await uploadCardImage(`${base}.webp`,images.full.file);await uploadCardImage(`${base}-thumb.webp`,images.thumbnail.file);}}setMessage('已上传匹配的漫画文件。请在知识点编辑页确认并写入对应图片路径。')}catch(error){setMessage(error instanceof Error?error.message:'上传失败。')}finally{setBusy(false)}};return <section className="admin-page"><Link to="/admin">← 返回后台</Link><h1>批量漫画匹配</h1><p>文件名必须为 <code>&lt;card-slug&gt;-question.png</code> 或 <code>&lt;card-slug&gt;-answer.png</code>。系统会浏览器端压缩成 WebP 并生成缩略图。</p><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>pick(e.target.files)}/>{files.length>0&&<ul>{files.map(file=>{const parsed=matchImageFilename(file.name);return <li>{file.name}：{parsed?`匹配 ${parsed.slug}（${parsed.kind}）`:'未匹配，跳过'}</li>})}</ul>}<button className="btn primary" disabled={busy||!files.length} onClick={upload}>{busy?'正在压缩上传…':'确认上传（每批 5 张）'}</button>{message&&<p className="form-message">{message}</p>}</section>}
export function UsagePage(){const [usage,setUsage]=useState<{cardCount:number;topicCount:number;imageCount:number;bytes:number;average:number}|null>(null);useEffect(()=>{estimateUsage().then(setUsage).catch(()=>setUsage(null));},[]);const mb=(value:number)=>(value/1024/1024).toFixed(2);return <section className="admin-page"><Link to="/admin">← 返回后台</Link><h1>免费额度用量估算</h1>{usage?<div className="usage"><p>知识点：<b>{usage.cardCount}</b></p><p>专题：<b>{usage.topicCount}</b></p><p>已读取图片文件：<b>{usage.imageCount}</b></p><p>图片总大小：<b>{mb(usage.bytes)} MB</b></p><p>平均每张：<b>{Math.round(usage.average/1024)} KB</b></p><p className={usage.bytes>850*1024*1024?'danger-text':usage.bytes>700*1024*1024?'warn-text':''}>实际流量和数据库用量请以 Supabase Dashboard 为准；本页不伪造流量统计。</p></div>:<p>正在读取内容统计，或云端尚未配置。</p>}</section>}
export function PlaceholderAdmin({title}:{title:string}){return <section className="admin-page"><Link to="/admin">← 返回后台</Link><h1>{title}</h1><p>此功能入口已保留。题目内容可通过 CSV 导入，图片可通过批量漫画匹配上传。</p></section>}
