import { supabase } from '../../lib/supabase/client';
import { supabaseErrorMessage } from '../../lib/supabase/errors';
import type { KnowledgeCard, Category } from '../../types/knowledge';

type CardRow = { id:string; question:string; answer:string; explanation:string; mnemonic:string|null; mistake_tip:string|null; question_type:'choice'|'recall'; option_a:string|null; option_b:string|null; option_c:string|null; option_d:string|null; correct_option:string|null; question_image_path:string|null; answer_image_path:string|null; question_thumbnail_path:string|null; answer_thumbnail_path:string|null; image_alt:string|null; difficulty:1|2|3; slug:string; topics:{ name:string; slug:string; categories:{ name:string; slug:string }|null }|null };
const categoryMap: Record<string, Category> = { 法律:'法律',历史:'历史',人文:'人文',科技:'科技',地理:'地理',经济:'经济',政治:'政治',趣味专题:'趣味' };
export type CloudCard = KnowledgeCard & { slug:string; questionType:'choice'|'recall'; options: Array<{key:'A'|'B'|'C'|'D';value:string}>; correctOption?:'A'|'B'|'C'|'D'; questionImagePath?:string; answerImagePath?:string; thumbnailPath?:string };
export function imageUrl(path?: string | null) { if (!path || !supabase) return undefined; return supabase.storage.from('card-images').getPublicUrl(path).data.publicUrl; }
function mapCard(row: CardRow): CloudCard { const topic = row.topics; const category = categoryMap[topic?.categories?.name ?? ''] ?? '趣味'; const options = ([['A',row.option_a],['B',row.option_b],['C',row.option_c],['D',row.option_d]] as const).filter((item):item is ['A',string]=>Boolean(item[1])).map(([key,value])=>({key,value})); return { id:row.id,slug:row.slug,question:row.question,answer:row.answer,explanation:row.explanation,mnemonic:row.mnemonic ?? undefined,mistakeTip:row.mistake_tip ?? undefined,category,topic:topic?.name ?? '未分类',tags:[topic?.categories?.name ?? '常识'],difficulty:row.difficulty,image:imageUrl(row.question_image_path),questionType:row.question_type,options,correctOption:(row.correct_option ?? undefined) as 'A'|'B'|'C'|'D'|undefined,questionImagePath:row.question_image_path ?? undefined,answerImagePath:row.answer_image_path ?? undefined,thumbnailPath:row.question_thumbnail_path ?? undefined,imageAlt:row.image_alt ?? undefined };
}
export async function fetchPublishedCards(page=0, pageSize=20, filters?:{query?:string;category?:string}) { if (!supabase) return { cards: [] as CloudCard[], count:0 }; const db:any=supabase; let query = db.from('knowledge_cards').select('id,slug,question,answer,explanation,mnemonic,mistake_tip,question_type,option_a,option_b,option_c,option_d,correct_option,question_image_path,answer_image_path,question_thumbnail_path,answer_thumbnail_path,image_alt,difficulty,topics!inner(name,slug,categories!inner(name,slug))',{count:'exact'}).eq('status','published').order('sort_order').range(page*pageSize,page*pageSize+pageSize-1); if(filters?.query) query=query.ilike('question',`%${filters.query}%`); if(filters?.category && filters.category!=='全部') query=query.eq('topics.categories.name',filters.category); const {data,error,count}=await query; if(error) throw new Error(supabaseErrorMessage(error)); return { cards:(data as CardRow[]).map(mapCard), count:count ?? 0 }; }
export async function fetchAllPublishedCards(limit=50) { return (await fetchPublishedCards(0,limit)).cards; }
export async function fetchCardById(id:string) { if(!supabase) return null; const {data,error}=await supabase.from('knowledge_cards').select('id,slug,question,answer,explanation,mnemonic,mistake_tip,question_type,option_a,option_b,option_c,option_d,correct_option,question_image_path,answer_image_path,question_thumbnail_path,answer_thumbnail_path,image_alt,difficulty,topics!inner(name,slug,categories!inner(name,slug))').eq('id',id).eq('status','published').maybeSingle(); if(error) throw new Error(supabaseErrorMessage(error)); return data ? mapCard(data as unknown as CardRow):null; }
