import { useEffect, useMemo, useRef, useState } from 'react';
import { HashRouter, Link, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, ChevronRight, Download, Heart, RotateCcw, Search, Settings2, Star, Upload, X } from 'lucide-react';
import { cards, categories, replaceCards } from './data/cards';
import { CardArt } from './components/CardArt';
import { EmptyState } from './components/EmptyState';
import { Page } from './components/Layout';
import { applyRating, blankRecord, todayQueue } from './lib/scheduler';
import { dayKey, formatDate } from './lib/date';
import { clearAll, exportData, importData, loadRecords, loadSessions, loadSettings, saveRecords, saveSessions, saveSettings } from './lib/storage';
import type { Category, KnowledgeCard } from './types/knowledge';
import type { Rating, ReviewRecord, StudySession, UserSettings } from './types/review';
import { AuthForm, AccountPage } from './features/auth/AuthPages';
import { useAuth } from './features/auth/useAuth';
import { AdminGuard, AdminHome, ImportPage, PlaceholderAdmin, StoragePage, UsagePage } from './features/admin/AdminPages';
import { fetchAllPublishedCards } from './features/cards/cardRepository';
import { mergeLocalData } from './features/progress/progressRepository';
import { isSupabaseConfigured } from './lib/supabase/client';

function useStore() { const [records,setRecords] = useState<Record<string,ReviewRecord>>(() => loadRecords()); const [settings,setSettings] = useState<UserSettings>(() => loadSettings()); const [sessions,setSessions] = useState<StudySession[]>(() => loadSessions()); useEffect(()=>saveRecords(records),[records]); useEffect(()=>saveSettings(settings),[settings]); useEffect(()=>saveSessions(sessions),[sessions]); return {records,setRecords,settings,setSettings,sessions,setSessions}; }
function useCardRecord(records: Record<string,ReviewRecord>, id: string) { return records[id] ?? blankRecord(id); }
function toggleFavorite(id:string, records:Record<string,ReviewRecord>, setRecords:React.Dispatch<React.SetStateAction<Record<string,ReviewRecord>>>) { setRecords(prev => ({...prev,[id]:{...(prev[id]??blankRecord(id)), favorite: !(prev[id]?.favorite)}})); }
function Progress({ value, max }: { value:number;max:number }) { return <div className="progress"><i style={{width:`${max ? Math.min(100,value/max*100):0}%`}}/></div>; }
function statusText(record?:ReviewRecord) { if (!record) return '未学习'; if (record.status === 'mastered') return '已掌握'; if (record.lastRating === 'forgot') return '待巩固'; if (record.status === 'reviewing') return '复习中'; return '学习中'; }

function Home({store}:{store:ReturnType<typeof useStore>}) { const {records,settings}=store; const queue=todayQueue(cards,records,settings); const learned=Object.keys(records).length, favorites=Object.values(records).filter(x=>x.favorite).length; const reviews=queue.filter(c=>!!records[c.id]).length; const topics=['法律','历史','人文','科技','地理','趣味'] as Category[]; return <Page><section className="hero"><div><p className="eyebrow">碎片时间，也能稳稳上岸</p><h1>一个考点，一幅漫画，<br/><strong>一分钟记住。</strong></h1><p className="lead">每天学 10 分钟，系统自动安排间隔复习。让你记得更牢，走得更稳。</p><div className="actions"><Link className="btn primary" to="/study">开始学习 <ArrowRight size={17}/></Link><Link className="btn ghost" to="/library">免费试背 20 张</Link></div></div><div className="hero-stack">{cards.slice(0,3).map((card,index)=><div className={`hero-card c${index}`} key={card.id}><span>{card.category}</span><CardArt category={card.category} image={card.image}/><b>{card.question}</b></div>)}</div></section><section className="stats-strip">{[[cards.length,'知识点总数'],[learned,'已学知识点'],[Math.max(1,Math.min(12,learned)),'连续学习天数'],[favorites,'收藏知识点']].map(([num,label],index)=><div key={String(label)}><span className={`stat-icon i${index}`}>{['▰','▣','▦','★'][index]}</span><p>{label}<b>{num}{index===0?'+':''}</b></p></div>)}</section><section><div className="section-title"><h2>热门专题</h2><Link to="/library">查看全部 <ChevronRight size={16}/></Link></div><div className="topic-grid">{topics.map(cat=><Link to={`/library?category=${cat}`} className="topic" key={cat}><CardArt category={cat}/><b>{cat}常识</b><small>{cards.filter(c=>c.category===cat).length} 个知识点</small></Link>)}</div></section><section className="today-preview"><div><p className="eyebrow">今日学习</p><h2>趁现在，完成一小步</h2><div className="task-counts"><span>新学 <b>{queue.filter(c=>!records[c.id]).length}</b> 个</span><span>复习 <b>{reviews}</b> 个</span><span>预计 <b>{Math.max(3,queue.length)}</b> 分钟</span></div></div><Link className="btn primary" to="/study">开始今日学习</Link></section></Page>; }

function Study({store}:{store:ReturnType<typeof useStore>}) { const {records,setRecords,settings,sessions,setSessions}=store; const [params]=useSearchParams(); const source=params.get('source') as 'mistakes'|'favorites'|null; const selectedCardId=params.get('card'); const makeQueue=()=>selectedCardId&&cards.some(card=>card.id===selectedCardId)?[selectedCardId]:todayQueue(cards,records,settings,source??undefined).map(card=>card.id); const [sessionIds,setSessionIds]=useState<string[]>(makeQueue); const queue=useMemo(()=>sessionIds.map(id=>cards.find(card=>card.id===id)).filter((card):card is KnowledgeCard=>Boolean(card)),[sessionIds]); const [index,setIndex]=useState(0); const [shown,setShown]=useState(false); const [ratings,setRatings]=useState<Rating[]>([]); const [started]=useState(Date.now()); const navigate=useNavigate(); useEffect(()=>{setSessionIds(makeQueue());setIndex(0);setShown(false);setRatings([])},[source,selectedCardId]); const card=queue[index]; const finished=!card || index>=queue.length;
  useEffect(()=>{ const onKey=(e:KeyboardEvent)=>{if (e.target instanceof HTMLInputElement) return; if(e.code==='Space'){e.preventDefault();setShown(true)} if(shown&&['1','2','3'].includes(e.key)) rate(['forgot','fuzzy','remembered'][Number(e.key)-1] as Rating); if(e.key.toLowerCase()==='f'&&card) toggleFavorite(card.id,records,setRecords);}; window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey); });
  function rate(rating:Rating) { if(!card || !shown) return; setRecords(prev=>({...prev,[card.id]:applyRating(prev[card.id],card.id,rating)})); setRatings(prev=>[...prev,rating]); window.setTimeout(()=>{setIndex(i=>i+1);setShown(false)}, settings.autoNext?180:0); }
  if(finished) { const summary={forgot:ratings.filter(r=>r==='forgot').length,fuzzy:ratings.filter(r=>r==='fuzzy').length,remembered:ratings.filter(r=>r==='remembered').length}; const save=()=>{const session:StudySession={id:crypto.randomUUID(),startedAt:new Date(started).toISOString(),completedAt:new Date().toISOString(),cardIds:queue.map(c=>c.id),ratings}; setSessions(s=>s.some(x=>x.startedAt===session.startedAt)?s:[session,...s]); navigate('/');}; return <Page><div className="summary"><span className="seal">学成</span><h1>这一轮完成了</h1><p>每一次认真回想，都是记忆在扎根。</p><div className="summary-grid"><b>{queue.length}<small>学习数量</small></b><b>{ratings.length-summary.forgot}<small>记住或模糊</small></b><b>{summary.forgot}<small>需要巩固</small></b><b>{Math.max(1,Math.round((Date.now()-started)/60000))}<small>用时（分钟）</small></b></div><div className="actions"><button className="btn primary" onClick={save}>返回首页</button><button className="btn ghost" onClick={()=>{setIndex(0);setShown(false);setRatings([])}}>再学一组</button></div></div></Page>; }
 const record=useCardRecord(records,card.id); return <Page><div className="study-layout"><aside className="study-aside"><p className="eyebrow">今日任务</p><h2>{source==='mistakes'?'错题巩固':source==='favorites'?'收藏复习':'今日学习'}</h2><div className="ratio"><b>{index+1}</b> / {queue.length}<Progress value={index} max={queue.length}/></div><p>新学 {queue.filter(c=>!records[c.id]).length} 个 · 复习 {queue.filter(c=>records[c.id]).length} 个</p><Link to="/settings">学习设置 <Settings2 size={15}/></Link></aside><article className="study-card"><div className="card-top"><span className={`badge ${card.category}`}>{card.category} · {card.topic}</span><button aria-label="收藏此知识点" className={record.favorite?'fav active':'fav'} onClick={()=>toggleFavorite(card.id,records,setRecords)}><Heart size={20} fill={record.favorite?'currentColor':'none'}/></button></div><h1>{card.question}</h1><CardArt category={card.category} image={card.image}/>{shown ? <div className="answer-panel"><p><b>标准答案</b>{card.answer}</p>{card.mnemonic&&<p><b>记忆口诀</b>{card.mnemonic}</p>}{card.mistakeTip&&<p><b>易错提醒</b>{card.mistakeTip}</p>}<p><b>简短解析</b>{card.explanation}</p></div> : <button className="reveal" onClick={()=>setShown(true)}>先想一想，点击查看答案</button>}{shown&&<div className="rating"><button onClick={()=>rate('forgot')}><X/>忘了<small>10 分钟后再来</small></button><button onClick={()=>rate('fuzzy')}><RotateCcw/>有点模糊<small>明天再复习</small></button><button onClick={()=>rate('remembered')}><Check/>记住了<small>间隔复习</small></button></div>}{settings.showShortcutHint&&<small className="hint">快捷键：空格查看答案 · 1 忘了 · 2 模糊 · 3 记住 · F 收藏</small>}</article></div></Page>; }

function Library({store}:{store:ReturnType<typeof useStore>}) { const {records}=store; const [params,setParams]=useSearchParams(); const [query,setQuery]=useState(''); const cat=params.get('category') ?? '全部'; const status=params.get('status') ?? '全部'; const result=cards.filter(c=>(cat==='全部'||c.category===cat)&&(status==='全部'||(status==='已掌握'?records[c.id]?.status==='mastered':status==='未学习'?!records[c.id]:!!records[c.id]))&&[c.question,c.answer,c.topic,...c.tags].join('').includes(query)); return <Page><section className="page-intro"><div><p className="eyebrow">题库</p><h1>把零散考点，收进脑海</h1></div><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索知识点、标签"/></label></section><div className="filters">{categories.map(x=><button className={cat===x?'selected':''} onClick={()=>setParams(x==='全部'?{}:{category:x})} key={x}>{x}</button>)}<span/>{['全部','未学习','学习中','已掌握'].map(x=><button className={status===x?'selected':''} onClick={()=>setParams(Object.fromEntries([['category',cat],['status',x]].filter(([,v])=>v!=='全部')))} key={x}>{x}</button>)}</div><div className="library-list">{result.map(card=><LibraryItem card={card} record={records[card.id]}/>)}</div>{!result.length&&<EmptyState title="没有找到对应知识点" description="换一个关键词或筛选条件试试看。"/>}</Page>; }
function LibraryItem({card,record}:{card:KnowledgeCard;record?:ReviewRecord}) { return <Link className="library-item" to={`/card/${card.id}`}><CardArt category={card.category} compact image={card.image}/><div><span className={`badge ${card.category}`}>{card.category}</span><h3>{card.question}</h3><p>{card.topic} · {card.tags.join(' · ')}</p></div><aside><b>{statusText(record)}</b><small>{record?.nextReviewAt?`下次复习：${formatDate(record.nextReviewAt)}`:'点击学习'}</small></aside></Link>; }

function Detail({store}:{store:ReturnType<typeof useStore>}) { const {id}=useParams(); const card=cards.find(c=>c.id===id); const {records,setRecords}=store; const [selected,setSelected]=useState<string[]>([]); const [submitted,setSubmitted]=useState(false); useEffect(()=>{setSelected([]);setSubmitted(false);},[id]); if(!card) return <Page><EmptyState title="这张卡片不见了" description="去题库继续探索吧。"/></Page>; const r=useCardRecord(records,card.id), index=cards.indexOf(card); const isMultiple=card.questionType==='multiple'; const hasOptions=Boolean(card.options?.length); const correctKeys=card.correctOptions?.length ? card.correctOptions : card.correctOption ? [card.correctOption] : []; const correct=submitted&&selected.length===correctKeys.length&&selected.every(key=>correctKeys.includes(key as typeof correctKeys[number])); const choose=(key:string)=>{if(submitted)return;setSelected(current=>isMultiple?(current.includes(key)?current.filter(item=>item!==key):[key]):[key]);}; const revealAnswer=()=>setSubmitted(true); return <Page><article className="detail"><Link to="/library" className="back"><ArrowLeft size={18}/> 返回题库</Link><div className="detail-head"><div><span className={`badge ${card.category}`}>{card.category} · {card.topic}</span><h1>{card.question}</h1><button className={r.favorite?'fav-label active':'fav-label'} onClick={()=>toggleFavorite(card.id,records,setRecords)}><Heart size={18} fill={r.favorite?'currentColor':'none'}/>{r.favorite?'已收藏':'收藏此卡'}</button></div><CardArt category={card.category} image={card.image}/></div>{hasOptions&&!submitted&&<section className="answer-choices"><p>{isMultiple?'多选题：请选择 1 个或多个答案。':'单选题：请选择一个答案。'}</p>{card.options?.map(option=><button type="button" key={option.key} className={selected.includes(option.key)?'selected':''} onClick={()=>choose(option.key)}><b>{option.key}</b><span>{option.value}</span></button>)}<button type="button" className="btn primary" disabled={!selected.length} onClick={revealAnswer}>确认答案</button></section>}{!hasOptions&&!submitted&&<section className="answer-choices recall-prompt"><p>这是一道问答题，请先在心里作答，再查看参考答案。</p><button type="button" className="btn primary" onClick={revealAnswer}>查看答案</button></section>}{submitted&&<><div className={hasOptions?`answer-result ${correct?'correct':'wrong'}`:'answer-result'}>{hasOptions?(correct?'回答正确！':'答案不正确，再看一下解析。'):'参考答案与解析'}</div><div className="detail-body"><p><b>标准答案</b>{card.answer}</p><p><b>记忆口诀</b>{card.mnemonic??'理解知识脉络，形成自己的关键词。'}</p>{card.mistakeTip&&<p><b>易错提醒</b>{card.mistakeTip}</p>}<p><b>知识解析</b>{card.explanation}</p></div></>}<div className="actions"><Link className="btn primary" to={`/study?card=${card.id}`}>学习此题</Link><Link className="btn ghost" to={`/card/${cards[(index+1)%cards.length].id}`}>下一条 <ArrowRight size={17}/></Link></div></article></Page>; }

function Mistakes({store}:{store:ReturnType<typeof useStore>}) { const {records,setRecords}=store; const list=cards.filter(c=>(records[c.id]?.mistakeCount??0)>0).sort((a,b)=>(records[b.id].mistakeCount-records[a.id].mistakeCount)); return <Page><section className="page-intro"><div><p className="eyebrow">错题本</p><h1>把遗忘，变成下一次记得</h1><p>每一张“忘了”的卡，都会在合适的时候回来找你。</p></div>{list.length>0&&<Link className="btn primary" to="/study?source=mistakes">开始错题复习</Link>}</section>{list.length?<div className="library-list">{list.map(c=><div className="mistake-row" key={c.id}><LibraryItem card={c} record={records[c.id]}/><div><b>累计错 {records[c.id].mistakeCount} 次</b><button onClick={()=>setRecords(p=>({...p,[c.id]:{...p[c.id],mistakeCount:0,status:'mastered'}}))}>标记已掌握</button></div></div>)}</div>:<EmptyState title="错题本还是空的" description="学习时遇到不确定的知识点，放心点“忘了”。" to="/study" action="开始学习"/>}</Page>; }
function Favorites({store}:{store:ReturnType<typeof useStore>}) { const {records,setRecords}=store; const list=cards.filter(c=>records[c.id]?.favorite); return <Page><section className="page-intro"><div><p className="eyebrow">收藏夹</p><h1>留住想再看一遍的考点</h1></div>{list.length>0&&<Link className="btn primary" to="/study?source=favorites">复习收藏夹</Link>}</section>{list.length?<div className="library-list">{list.map(c=><div className="favorite-row" key={c.id}><LibraryItem card={c} record={records[c.id]}/><button className="fav active" aria-label="取消收藏" onClick={()=>toggleFavorite(c.id,records,setRecords)}><Heart fill="currentColor"/></button></div>)}</div>:<EmptyState title="收藏夹还没有卡片" description="点击学习卡右上角的爱心，把重点留在这里。"/>}</Page>; }

function Stats({store}:{store:ReturnType<typeof useStore>}) { const {records,sessions}=store; const all=Object.values(records), learned=all.length, mastered=all.filter(x=>x.status==='mastered').length; const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=dayKey(d);return {key,label:new Intl.DateTimeFormat('zh-CN',{weekday:'short'}).format(d),value:sessions.filter(s=>dayKey(new Date(s.completedAt))===key).reduce((n,s)=>n+s.cardIds.length,0)}}); const max=Math.max(1,...days.map(d=>d.value)); return <Page><section className="page-intro"><div><p className="eyebrow">学习数据</p><h1>每一点积累，都算数</h1></div></section><div className="metric-grid">{[[sessions.filter(s=>dayKey(new Date(s.completedAt))===dayKey()).reduce((n,s)=>n+s.cardIds.length,0),'今日学习'],[sessions.reduce((n,s)=>n+s.cardIds.length,0),'累计学习'],[mastered,'已掌握'],[Math.max(0,Math.min(12,learned)),'连续学习天数']].map(([n,l])=><div><b>{n}</b><small>{l}</small></div>)}</div><section className="chart-card"><h2>最近 7 天学习</h2><div className="bar-chart">{days.map(d=><div><span style={{height:`${Math.max(6,d.value/max*100)}%`}} title={`${d.value} 张`}/><small>{d.label}</small></div>)}</div></section><section className="progress-section"><div><h2>掌握度分布</h2><div className="mastery"><b>{learned?Math.round(mastered/learned*100):0}%</b><span>已掌握</span></div></div><div className="category-progress"><h2>分类学习进度</h2>{categories.slice(1).map(cat=>{const allCards=cards.filter(c=>c.category===cat);const done=allCards.filter(c=>records[c.id]).length;return <p><span>{cat}</span><Progress value={done} max={allCards.length}/><b>{done}/{allCards.length}</b></p>})}</div></section></Page>; }

function Settings({store}:{store:ReturnType<typeof useStore>}) { const {settings,setSettings,setRecords,setSessions}=store; const input=useRef<HTMLInputElement>(null); const download=()=>{const blob=new Blob([exportData()],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`上岸小卡学习数据-${dayKey()}.json`;a.click();URL.revokeObjectURL(url)}; const importFile=(f?:File)=>{if(!f)return;const reader=new FileReader();reader.onload=()=>{try{importData(String(reader.result));window.location.reload()}catch{alert('导入失败：请选择由上岸小卡导出的 JSON 文件。')}};reader.readAsText(f)}; return <Page><section className="settings"><p className="eyebrow">设置</p><h1>按你的节奏学习</h1><Setting label="每日新学数量" hint="系统会在复习任务后补充新卡">{([10,15,20] as const).map(n=><button className={settings.dailyNewCount===n?'selected':''} onClick={()=>setSettings(s=>({...s,dailyNewCount:n}))}>{n} 张</button>)}</Setting><Setting label="每日复习上限" hint="避免任务堆积，也不遗漏关键复习">{([20,30,50,9999] as const).map(n=><button className={settings.dailyReviewLimit===n?'selected':''} onClick={()=>setSettings(s=>({...s,dailyReviewLimit:n}))}>{n===9999?'不限':`${n} 张`}</button>)}</Setting><Setting label="自动进入下一张" hint="评价后以轻微切换继续学习"><Toggle on={settings.autoNext} set={v=>setSettings(s=>({...s,autoNext:v}))}/></Setting><Setting label="显示快捷键提示" hint="键盘学习更顺手"><Toggle on={settings.showShortcutHint} set={v=>setSettings(s=>({...s,showShortcutHint:v}))}/></Setting><Setting label="本地数据" hint="数据只存储在当前浏览器中"><button onClick={download}><Download size={16}/>导出 JSON</button><button onClick={()=>input.current?.click()}><Upload size={16}/>导入 JSON</button><input ref={input} hidden type="file" accept="application/json" onChange={e=>importFile(e.target.files?.[0])}/><button className="danger" onClick={()=>{if(confirm('确定要清空全部学习记录吗？此操作无法撤销。')&&confirm('请再次确认：学习记录、收藏和设置都会被清空。')){clearAll();setRecords({});setSessions([]);window.location.reload()}}}>清空学习记录</button></Setting></section></Page>; }
function Setting({label,hint,children}:{label:string;hint:string;children:React.ReactNode}) { return <div className="setting"><div><h2>{label}</h2><p>{hint}</p></div><div className="setting-controls">{children}</div></div>; }
function Toggle({on,set}:{on:boolean;set:(v:boolean)=>void}) { return <button className={`toggle ${on?'on':''}`} onClick={()=>set(!on)} aria-label="切换设置"><i/></button>; }
function NotFound(){return <Page><EmptyState title="这页找不到了" description="回到首页继续学习吧。" to="/" action="返回首页"/></Page>}
function AdminRoute({auth,children}:{auth:ReturnType<typeof useAuth>;children:React.ReactNode}){return <Page><AdminGuard isAdmin={auth.isAdmin}>{children}</AdminGuard></Page>}
function AppRoutes(){const store=useStore();const auth=useAuth();const [,setCardVersion]=useState(0);useEffect(()=>{if(!isSupabaseConfigured)return;fetchAllPublishedCards(50).then(remote=>{if(remote.length){replaceCards(remote);setCardVersion(version=>version+1);}}).catch(()=>undefined);},[]);const merge=async()=>{if(!auth.user)throw new Error('请先登录。');const remote=await fetchAllPublishedCards(50);await mergeLocalData(auth.user.id,remote);};return <><div className={`cloud-mode ${isSupabaseConfigured?'':'local'}`}>{isSupabaseConfigured?(auth.user?'云端同步已连接':'游客模式：登录后可跨设备同步'):'本地演示模式：配置 Supabase 后可启用云端同步'}</div><Routes><Route path="/" element={<Home store={store}/>}/><Route path="/study" element={<Study store={store}/>}/><Route path="/library" element={<Library store={store}/>}/><Route path="/card/:id" element={<Detail store={store}/>}/><Route path="/mistakes" element={<Mistakes store={store}/>}/><Route path="/favorites" element={<Favorites store={store}/>}/><Route path="/stats" element={<Stats store={store}/>}/><Route path="/settings" element={<Settings store={store}/>}/><Route path="/login" element={<AuthForm mode="login"/>}/><Route path="/register" element={<AuthForm mode="register"/>}/><Route path="/account" element={<AccountPage user={auth.user} role={auth.role} onMerge={merge}/>}/><Route path="/admin" element={<AdminRoute auth={auth}><AdminHome/></AdminRoute>}/><Route path="/admin/cards" element={<AdminRoute auth={auth}><PlaceholderAdmin title="知识点管理"/></AdminRoute>}/><Route path="/admin/cards/new" element={<AdminRoute auth={auth}><PlaceholderAdmin title="新建知识点"/></AdminRoute>}/><Route path="/admin/cards/:id/edit" element={<AdminRoute auth={auth}><PlaceholderAdmin title="编辑知识点"/></AdminRoute>}/><Route path="/admin/topics" element={<AdminRoute auth={auth}><PlaceholderAdmin title="专题管理"/></AdminRoute>}/><Route path="/admin/import" element={<AdminRoute auth={auth}><ImportPage/></AdminRoute>}/><Route path="/admin/storage" element={<AdminRoute auth={auth}><StoragePage/></AdminRoute>}/><Route path="/admin/usage-guide" element={<AdminRoute auth={auth}><UsagePage/></AdminRoute>}/><Route path="*" element={<NotFound/>}/></Routes></>}
export default function App(){return <HashRouter><AppRoutes/></HashRouter>}
