alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.topics enable row level security; alter table public.knowledge_cards enable row level security; alter table public.user_card_progress enable row level security; alter table public.favorites enable row level security; alter table public.wrong_answers enable row level security; alter table public.study_sessions enable row level security; alter table public.user_settings enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create or replace function public.prevent_profile_role_change() returns trigger language plpgsql security definer set search_path = public as $$ begin if new.role is distinct from old.role and not public.is_admin() then raise exception 'role cannot be changed'; end if; return new; end; $$;
drop trigger if exists profiles_role_guard on public.profiles; create trigger profiles_role_guard before update on public.profiles for each row execute procedure public.prevent_profile_role_change();

create policy "read active categories" on public.categories for select using (is_active or public.is_admin()); create policy "admin categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "read active topics" on public.topics for select using (is_active or public.is_admin()); create policy "admin topics" on public.topics for all using (public.is_admin()) with check (public.is_admin());
create policy "read published cards" on public.knowledge_cards for select using (status='published' or public.is_admin()); create policy "admin cards" on public.knowledge_cards for all using (public.is_admin()) with check (public.is_admin());
create policy "read own profile" on public.profiles for select using (id=auth.uid()); create policy "update own profile" on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());
create policy "own progress" on public.user_card_progress for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy "own favorites" on public.favorites for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy "own wrong answers" on public.wrong_answers for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy "own sessions" on public.study_sessions for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy "own settings" on public.user_settings for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "public read card images" on storage.objects for select using (bucket_id='card-images'); create policy "admin manage card images" on storage.objects for all using (bucket_id='card-images' and public.is_admin()) with check (bucket_id='card-images' and public.is_admin()); create policy "admin private images" on storage.objects for all using (bucket_id='private-card-images' and public.is_admin()) with check (bucket_id='private-card-images' and public.is_admin());
