insert into public.categories(name,slug,icon,sort_order) values
('法律','law','⚖',1),('历史','history','🏯',2),('人文','culture','📜',3),('科技','science','⚙',4),('地理','geography','⛰',5),('经济','economy','◈',6),('政治','politics','✦',7),('趣味专题','fun','🏺',8) on conflict(slug) do update set name=excluded.name;
insert into public.topics(category_id,name,slug,sort_order) values
((select id from public.categories where slug='law'),'宪法','constitution',1),((select id from public.categories where slug='law'),'法制史','legal-history',2),((select id from public.categories where slug='history'),'汉代','han-dynasty',1),((select id from public.categories where slug='history'),'隋唐','sui-tang',2),((select id from public.categories where slug='culture'),'道家','taoism',1),((select id from public.categories where slug='culture'),'墨家','mohism',2),((select id from public.categories where slug='science'),'航天','space',1),((select id from public.categories where slug='science'),'生命科学','life-science',2),((select id from public.categories where slug='geography'),'中国地理','china-geography',1),((select id from public.categories where slug='geography'),'地球运动','earth-motion',2),((select id from public.categories where slug='economy'),'宏观经济','macro-economy',1),((select id from public.categories where slug='politics'),'政治制度','political-system',1),((select id from public.categories where slug='fun'),'文化常识','culture-fun',1) on conflict(slug) do nothing;

insert into public.knowledge_cards(topic_id,slug,status,question_type,question,answer,explanation,mnemonic,mistake_tip,option_a,option_b,option_c,option_d,correct_option,difficulty,sort_order,published_at) values
((select id from public.topics where slug='space'),'dongfanghong-1','published','choice','我国第一颗人造地球卫星叫什么？','东方红一号','1970年4月24日，我国成功发射第一颗人造地球卫星“东方红一号”。','东方升起第一星，红色卫星绕地行。','嫦娥一号是月球探测卫星，神舟一号是无人试验飞船。','风云一号','东方红一号','嫦娥一号','神舟一号','B',1,1,now()),
((select id from public.topics where slug='constitution'),'constitution-amendment','published','choice','我国宪法修正案需要全国人大以多少票数通过？','全体代表的三分之二以上多数。','宪法修改必须由全国人大以全体代表三分之二以上多数通过。','全体代表，三分之二。','不是到会代表的三分之二，而是全体代表的三分之二以上。','到会代表过半数','全体代表过半数','全体代表三分之二以上','到会代表三分之二以上','C',2,1,now()),
((select id from public.topics where slug='taoism'),'zhuangzhou-nanhua','published','recall','庄周又被称为什么？','南华真人。','唐玄宗追封庄子为南华真人，《庄子》也被称为《南华经》。','庄周梦蝶，南华真人。',null,null,null,null,null,null,1,1,now()),
((select id from public.topics where slug='taoism'),'zhuangzhou-butterfly','published','recall','“庄周梦蝶”体现了什么思想？','体现了道家对物我关系、真实与梦境边界的思考。','故事以梦蝶引出物化的哲思，强调万物变化与主体认知的相对性。','梦蝶问真，物我相通。',null,null,null,null,null,null,2,2,now()),
((select id from public.topics where slug='legal-history'),'fa-jing','published','choice','我国第一部较系统的封建成文法典是什么？','《法经》。','《法经》由战国魏国李悝制定，对后世封建法制有重要影响。','李悝写《法经》。',null,'《法经》','《唐律疏议》','《大明律》','《法典》','A',1,1,now()),
((select id from public.topics where slug='mohism'),'mozi-thought','published','recall','墨子的主要思想有哪些？','兼爱、非攻、尚贤、节用。','墨家主张兼相爱、交相利，反对不义战争，重视贤能与节俭。','兼爱非攻，尚贤节用。',null,null,null,null,null,null,1,1,now()),
((select id from public.topics where slug='han-dynasty'),'wenjing-rule','published','choice','“文景之治”发生在哪个朝代？','西汉。','汉文帝、汉景帝时期实行轻徭薄赋、与民休息政策。','文景治世在西汉。',null,'西汉','东汉','唐朝','宋朝','A',1,1,now()),
((select id from public.topics where slug='sui-tang'),'imperial-exam','published','choice','科举制度正式创立于哪个朝代？','隋朝。','隋炀帝始设进士科，标志着科举制度正式创立。','隋朝进士，科举开篇。',null,'秦朝','隋朝','唐朝','宋朝','B',1,1,now()),
((select id from public.topics where slug='han-dynasty'),'shiji','published','recall','《史记》的作者是谁？','司马迁。','《史记》是中国第一部纪传体通史。','迁写史记，纪传通史。',null,null,null,null,null,null,1,2,now()),
((select id from public.topics where slug='science'),'bi-sheng','published','choice','活字印刷术的发明者是谁？','北宋毕昇。','毕昇发明胶泥活字印刷术，比欧洲活字印刷早数百年。','北宋毕昇，活字留名。',null,'蔡伦','毕昇','沈括','祖冲之','B',1,1,now()),
((select id from public.topics where slug='life-science'),'skin','published','recall','人体中最大的器官是什么？','皮肤。','皮肤覆盖人体表面，具有保护、感觉、调节体温等作用。','最大器官是皮肤。',null,null,null,null,null,null,1,1,now()),
((select id from public.topics where slug='earth-motion'),'earth-rotation','published','choice','地球自转一周约需要多长时间？','24小时。','以太阳为参照，地球完成一次自转形成一个昼夜，约为24小时。','地球自转，一日二十四。',null,'12小时','24小时','30天','365天','B',1,1,now()),
((select id from public.topics where slug='china-geography'),'xinjiang','published','recall','我国面积最大的省级行政区是哪里？','新疆维吾尔自治区。','新疆维吾尔自治区是我国陆地面积最大的省级行政区。','最大省区在新疆。',null,null,null,null,null,null,1,1,now()),
((select id from public.topics where slug='china-geography'),'yangtze-east-sea','published','choice','长江最终注入哪个海域？','东海。','长江在上海市崇明岛以东注入东海。','长江东流入东海。',null,'渤海','黄海','东海','南海','C',1,2,now()),
((select id from public.topics where slug='macro-economy'),'inflation','published','recall','通货膨胀通常指什么？','一般物价水平持续上涨、货币购买力下降的经济现象。','它是宏观经济中的价格现象，不等同于某一种商品涨价。','物价普涨，购买力降。',null,null,null,null,null,null,2,1,now()),
((select id from public.topics where slug='macro-economy'),'market-mechanism','published','recall','市场配置资源主要通过什么机制实现？','价格、供求和竞争机制。','市场价格反映供求变化，引导生产要素流向效率更高的领域。','价格供求加竞争。',null,null,null,null,null,null,1,2,now()),
((select id from public.topics where slug='political-system'),'people-congress','published','choice','我国的根本政治制度是什么？','人民代表大会制度。','人民代表大会制度是中国人民当家作主的根本途径和最高实现形式。','根本制度，人大制度。',null,'人民代表大会制度','民族区域自治制度','基层群众自治制度','中国共产党领导的多党合作制度','A',1,1,now()),
((select id from public.topics where slug='political-system'),'democratic-centralism','published','recall','中国共产党的根本组织原则是什么？','民主集中制。','民主集中制是在民主基础上的集中和在集中指导下的民主相结合。','民主基础，集中指导。',null,null,null,null,null,null,2,2,now()),
((select id from public.topics where slug='culture-fun'),'pacific','published','choice','世界上面积最大的海洋是什么？','太平洋。','太平洋是面积最大、最深的海洋。','海洋最大太平洋。',null,'大西洋','太平洋','印度洋','北冰洋','B',1,1,now()),
((select id from public.topics where slug='culture-fun'),'mount-tai','published','recall','“五岳”之首是哪座山？','泰山。','五岳为东岳泰山、西岳华山、南岳衡山、北岳恒山、中岳嵩山。','五岳之首是泰山。',null,null,null,null,null,null,1,2,now()),
((select id from public.topics where slug='political-system'),'flag-star','published','recall','我国国旗上的大星代表什么？','中国共产党。','五星红旗中大星代表中国共产党，四颗小星代表人民群众。','一大四小，党与人民。',null,null,null,null,null,null,1,3,now()),
((select id from public.topics where slug='china-geography'),'grand-canal','published','recall','京杭大运河沟通了哪五大水系？','海河、黄河、淮河、长江、钱塘江。','京杭大运河是世界上里程最长、工程最大的古代运河之一。','海黄淮长钱，运河一线牵。',null,null,null,null,null,null,2,3,now()),
((select id from public.topics where slug='culture-fun'),'blue-white-porcelain','published','choice','“青花瓷”主要以哪种颜色为装饰？','蓝色。','青花瓷以钴料着色，经高温烧成呈蓝色。','白地蓝花青花瓷。',null,'红色','蓝色','绿色','黄色','B',1,3,now()),
((select id from public.topics where slug='constitution'),'constitution-root','published','recall','为什么说宪法是国家根本法？','它规定国家最根本、最重要的问题，具有最高法律效力，制定和修改程序更严格。','宪法是其他法律的立法依据，任何法律不得同宪法相抵触。','内容最根本，效力最高，程序最严。',null,null,null,null,null,null,2,2,now())
on conflict(slug) do nothing;
